import Project, { DataSetType } from "../models/Project";
import { D2Api, Id } from "../types/d2-api";
import { getUid } from "../utils/dhis2";

type CategoryOption = { id: Id; name: string };
type Category = { id: Id; name: string; categoryOptions: CategoryOption[] };
type CategoryOptionCombo = { id: Id; name: string; categoryOptions: { id: Id }[] };
type CategoryCombo = {
    id: Id;
    name: string;
    categories: Category[];
    categoryOptionCombos: CategoryOptionCombo[];
};
type DataElement = {
    id: Id;
    name: string;
    formName?: string;
    categoryCombo: CategoryCombo;
};
type Section = { id: Id; name: string; dataElements: DataElement[] };
type DataSet = { id: Id; name: string; sections: Section[] };

type Group = { categoryCombo: CategoryCombo; elements: DataElement[] };
type GroupOptions = { valueColumns: number; maxValueColumns: number };

/* Width of the column of names, as a percentage of the width of the section. */
const nameColumnWidth = 45;
const valueColumnName = "Value";
const dataElementColumnName = "Data element";

export class DataSetCustomForm {
    constructor(private api: D2Api) {}

    async generate(dataSetId: Id): Promise<string> {
        const dataSet = await this.fetchDataSet(dataSetId);
        if (!dataSet) return "";
        return this.buildHtml(dataSet);
    }

    async saveCustomForm(
        dataSetId: Id,
        project: Project,
        dataSetType: DataSetType
    ): Promise<Id | undefined> {
        const dataEntryForm = await this.generate(dataSetId);
        if (!dataEntryForm) return undefined;

        const customFormId = getUid("dataEntryForm", dataSetId);
        const labelType = dataSetType === "actual" ? "Actual" : "Target";

        const dataSetMetadata = await this.api.models.dataSets
            .getById(dataSetId, { fields: { $owner: true } })
            .getData();

        const metadata = {
            dataEntryForms: [
                {
                    id: customFormId,
                    /* DHIS2 requires the name of a data entry form to be unique, and two projects
                       may share the same name (only the code is validated as unique), so include the
                       project id, as the short name of the data set does. */
                    name: `${project.name} [${project.code}] ${labelType}`,
                    style: "NORMAL" as const,
                    htmlCode: dataEntryForm,
                },
            ],
            dataSets: [{ ...dataSetMetadata, dataEntryForm: { id: customFormId } }],
        };

        await this.api.metadata.post(metadata).getData();

        return customFormId;
    }

    /* The report of the data approval screen is generated by the server from the custom form when
       the data set has one, and that report has no section names, no column headers and no totals.
       Removing the form gives the report generated from the sections instead, and nothing is lost:
       data entry saves it again whenever it is opened. It is deleted and not only detached, as a
       form that no data set references is no longer deleted along with its data set and would keep
       its name, which the API requires to be unique. */
    async removeCustomForm(dataSetId: Id): Promise<void> {
        const dataSet = await this.api.models.dataSets
            .getById(dataSetId, { fields: { $owner: true } })
            .getData();

        const { dataEntryForm } = dataSet;
        if (!dataEntryForm) return;

        await this.api.models.dataEntryForms.delete(dataEntryForm).getData();
    }

    private async fetchDataSet(id: Id): Promise<DataSet | undefined> {
        const res = await this.api.metadata
            .get({
                dataSets: {
                    fields: {
                        id: true,
                        name: true,
                        sections: {
                            id: true,
                            name: true,
                            dataElements: {
                                id: true,
                                name: true,
                                formName: true,
                                categoryCombo: {
                                    id: true,
                                    name: true,
                                    categories: {
                                        id: true,
                                        name: true,
                                        categoryOptions: { id: true, name: true },
                                    },
                                    categoryOptionCombos: {
                                        id: true,
                                        name: true,
                                        categoryOptions: { id: true },
                                    },
                                },
                            },
                        },
                    },
                    filter: { id: { eq: id } },
                },
            })
            .getData()
            .catch(() => undefined);
        const ds = res?.dataSets[0];
        if (!ds) return undefined;
        return ds as unknown as DataSet;
    }

    private buildHtml(ds: DataSet): string {
        const sections = ds.sections;
        const tabs = sections
            .map(
                (s, i) =>
                    `<button type="button" class="cf-tab${
                        i === 0 ? " selected" : ""
                    }" data-section="${s.id}">${escapeHtml(s.name)}</button>`
            )
            .join("");
        const panels = sections.map((s, i) => this.renderSection(s, i === 0)).join("");
        return [
            `<style>${this.styles()}</style>`,
            `<div class="cf-wrapper">`,
            `  <div class="cf-tabs">${tabs}</div>`,
            `  <div class="cf-panels">${panels}</div>`,
            `</div>`,
            `<script>${this.script()}</script>`,
        ].join("\n");
    }

    /* The server-side data set report (used by the data approval screen) builds one grid per table,
       taking its first row as the header and discarding every row with a different number of
       columns. So each category combo needs a table of its own, and the title of the section and
       the filter are rendered outside of them: otherwise the data elements of every group but the
       first are dropped from the report. */
    private renderSection(section: Section, active: boolean): string {
        const groups = groupByCategoryCombo(section.dataElements);
        const columnsByGroup = groups.map(group => this.getValueColumns(group));
        const maxColumns = Math.max(...columnsByGroup);
        const tables = groups
            .map((group, index) =>
                this.renderGroup(group, {
                    valueColumns: columnsByGroup[index],
                    maxValueColumns: maxColumns,
                })
            )
            .join("\n  ");
        return `<div class="cf-panel${active ? " active" : ""}" data-section="${section.id}">
  <div class="cf-section-header">${escapeHtml(section.name)}</div>
  <div class="cf-filter-cell"><input type="text" class="cf-filter" placeholder="Type here to filter rows in this section"/></div>
  ${tables}
</div>`;
    }

    private getValueColumns(group: Group): number {
        const { categoryCombo: cc } = group;
        return cc.name === "default" ? 1 : this.orderedCocs(cc).length;
    }

    /* All the groups of a section show their values in columns of the same width, as if they still
       shared a single table: the table of a group with fewer values is narrower instead of
       stretching its columns to fill the section. */
    private getGroupWidths(valueColumns: number, maxValueColumns: number) {
        const valueWidth = (100 - nameColumnWidth) / maxValueColumns;
        const tableWidth = nameColumnWidth + valueWidth * valueColumns;

        return {
            table: percent(tableWidth),
            nameCell: percent((nameColumnWidth / tableWidth) * 100),
        };
    }

    /* The report takes the first row of the table as the header of its grid, so a row naming the
       columns is added before the visible ones and hidden by the styles: the form is rendered by a
       browser, which never shows it, while the report parses the HTML and does read it. Without it
       the report would use the first row of category names, whose cells span several columns. */
    private renderReportHeader(columnNames: string[]): string {
        const columns = columnNames.map(name => `<th>${escapeHtml(name)}</th>`).join("");
        return `<tr class="cf-report-header"><th>${dataElementColumnName}</th>${columns}</tr>`;
    }

    private renderGroup(group: Group, options: GroupOptions): string {
        const { valueColumns, maxValueColumns } = options;
        const { categoryCombo: cc, elements } = group;
        const widths = this.getGroupWidths(valueColumns, maxValueColumns);
        const isDefault = cc.name === "default";
        if (isDefault) {
            const coc = cc.categoryOptionCombos[0];
            const rows = elements
                .map(
                    de =>
                        `<tr class="cf-data-row"><td class="cf-de-name">${escapeHtml(
                            formNameOf(de)
                        )}</td><td class="cf-cell"><input id="${de.id}-${
                            coc.id
                        }-val" name="entryfield" title="${escapeHtml(de.name)}"/></td></tr>`
                )
                .join("");
            return `<table class="cf-table" style="width:${widths.table}">
  ${this.renderReportHeader([valueColumnName])}
  <tr><th class="cf-cat-corner" style="width:${
      widths.nameCell
  }"></th><th class="cf-cat-header">${valueColumnName}</th></tr>
  ${rows}
</table>`;
        }
        const cats = cc.categories;
        const headerRows = this.renderCategoryHeaders(cats, widths.nameCell);
        const colCocs = this.orderedCocs(cc);
        const rows = elements
            .map(de => {
                const cells = colCocs
                    .map(
                        coc =>
                            `<td class="cf-cell"><input id="${de.id}-${
                                coc.id
                            }-val" name="entryfield" title="${escapeHtml(de.name)}"/></td>`
                    )
                    .join("");
                return `<tr class="cf-data-row"><td class="cf-de-name">${escapeHtml(
                    formNameOf(de)
                )}</td>${cells}</tr>`;
            })
            .join("");
        return `<table class="cf-table" style="width:${widths.table}">
  ${this.renderReportHeader(colCocs.map(coc => coc.name))}
  ${headerRows}
  ${rows}
</table>`;
    }

    private renderCategoryHeaders(cats: Category[], nameCellWidth: string): string {
        const counts = cats.map(c => c.categoryOptions.length);
        return cats
            .map((cat, i) => {
                const colspan = counts.slice(i + 1).reduce((a, b) => a * b, 1);
                const repeats = counts.slice(0, i).reduce((a, b) => a * b, 1);
                const cells = Array.from({ length: repeats })
                    .flatMap(() => cat.categoryOptions)
                    .map(
                        opt =>
                            `<th class="cf-cat-header" colspan="${colspan}">${escapeHtml(
                                opt.name
                            )}</th>`
                    )
                    .join("");
                /* The table has a fixed layout, so only the first row defines the columns. */
                const width = i === 0 ? ` style="width:${nameCellWidth}"` : "";
                return `<tr><th class="cf-cat-name"${width}>${escapeHtml(
                    cat.name
                )}</th>${cells}</tr>`;
            })
            .join("");
    }

    private orderedCocs(cc: CategoryCombo): CategoryOptionCombo[] {
        const cartesian = cc.categories.reduce<string[][]>(
            (acc, cat) => acc.flatMap(prev => cat.categoryOptions.map(opt => [...prev, opt.id])),
            [[]]
        );
        const cocByKey = new Map<string, CategoryOptionCombo>();
        for (const coc of cc.categoryOptionCombos) {
            const key = coc.categoryOptions
                .map(o => o.id)
                .sort()
                .join(",");
            cocByKey.set(key, coc);
        }
        return cartesian.map(ids => {
            const key = [...ids].sort().join(",");
            const coc = cocByKey.get(key);
            if (!coc)
                throw new Error(
                    `CategoryOptionCombo not found in categoryCombo ${cc.id} for options: ${key}`
                );
            return coc;
        });
    }

    private styles(): string {
        return `
.cf-wrapper, .cf-wrapper * { font-family: Roboto, sans-serif; box-sizing: border-box; }
.cf-wrapper { color: #212934; }
.cf-tabs { display: flex; border-bottom: 1px solid #d5dae0; margin-bottom: 8px; flex-wrap: wrap; }
.cf-tabs .cf-tab { background: none; border: none; padding: 12px 16px; cursor: pointer; font-size: 14px; color: #4a5768; border-bottom: 3px solid transparent; font-family: Roboto, sans-serif; }
.cf-tabs .cf-tab.selected { color: #2c6693; border-bottom-color: #2c6693; font-weight: 500; }
.cf-panel { display: none; }
.cf-panel.active { display: block; }
/* The width of each table and of its first column are set when the form is generated, so that the
   columns of values of a section are all of the same width. */
.cf-table { border-collapse: collapse; table-layout: fixed; }
.cf-table + .cf-table { margin-top: -1px; }
/* Read by the data set report, never shown in data entry: it must be display none, as a hidden row
   that still generated a box would take part in the layout of the table. */
.cf-report-header { display: none; }
.cf-section-header { display: block; background-color: #404b5a; color: #fff; text-align: left; padding: 10px 14px; font-weight: 500; font-size: 14px; }
.cf-filter-cell { display: block; padding: 8px; background: #fff; border: 1px solid #e8edf2; border-bottom: 0; }
.cf-filter { width: 100%; padding: 6px 10px; border: 1px solid #d5dae0; border-radius: 3px; font-size: 13px; font-family: Roboto, sans-serif; }
.cf-cat-header, .cf-cat-name, .cf-cat-corner { background-color: #f3f5f7; color: #000; font-weight: 500; padding: 8px 10px; border: 1px solid #e8edf2; font-size: 13px; }
.cf-cat-header { text-align: center; }
.cf-cat-name { text-align: left; }
.cf-de-name { background-color: #fff; padding: 8px 10px; border: 1px solid #e8edf2; font-size: 13px; }
.cf-cell { background-color: #fff; padding: 0; border: 1px solid #e8edf2; }
.cf-cell .field-wrapper { display: block !important; width: 100%; }
.cf-cell input { width: 100%; box-sizing: border-box; border: none; padding: 8px 10px; font-size: 13px; text-align: right; outline: none; background: transparent; font-family: Roboto, sans-serif; }
.cf-cell input:focus { background: #e8f0fa; }
`;
    }

    private script(): string {
        return `
(function() {
  document.querySelectorAll('.cf-wrapper').forEach(function(wrapper) {
    var tabs = wrapper.querySelectorAll('.cf-tab');
    var panels = wrapper.querySelectorAll('.cf-panel');
    tabs.forEach(function(tab) {
      tab.addEventListener('click', function() {
        var id = tab.getAttribute('data-section');
        tabs.forEach(function(t) { t.classList.remove('selected'); });
        tab.classList.add('selected');
        panels.forEach(function(p) {
          p.classList.toggle('active', p.getAttribute('data-section') === id);
        });
      });
    });
    wrapper.querySelectorAll('.cf-filter').forEach(function(input) {
      input.addEventListener('input', function() {
        var term = input.value.toLowerCase();
        var panel = input.closest('.cf-panel');
        if (!panel) return;
        panel.querySelectorAll('tr.cf-data-row').forEach(function(row) {
          var nameCell = row.querySelector('.cf-de-name');
          if (!nameCell) return;
          var match = nameCell.textContent.toLowerCase().indexOf(term) !== -1;
          row.style.display = match ? '' : 'none';
        });
      });
    });
  });
})();
`;
    }
}

function percent(value: number): string {
    return `${Math.round(value * 100) / 100}%`;
}

function formNameOf(de: DataElement): string {
    return de.formName || de.name;
}

function escapeHtml(s: string): string {
    return s
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");
}

function groupByCategoryCombo(des: DataElement[]): Group[] {
    const groups: Group[] = [];
    const idx = new Map<Id, number>();
    for (const de of des) {
        const ccId = de.categoryCombo.id;
        const at = idx.get(ccId);
        if (at !== undefined) {
            groups[at].elements.push(de);
        } else {
            idx.set(ccId, groups.length);
            groups.push({ categoryCombo: de.categoryCombo, elements: [de] });
        }
    }
    return groups;
}
